### ISSUE TITLE
help with services.jar

### ISSUE THREAD

**Issue by Flatzki** [MiCode/legacy-patchrom#12]
hi, i have a prob with services.jar 

this is my error

  inflating: .build/ZIP/system/xbin/vim  
  inflating: .build/ZIP/system/build.prop  
## build .build/services.jar...

cp -r services.jar.out/ .build/services
/home/flatzki/patchrom/tools/add_miui_smail.sh .build/services_miui .build/services
/home/flatzki/patchrom/tools/apktool b .build/services .build/services.jar
I: Checking whether sources has changed...
W: Could not find resources
I: Building apk file...
Exception in thread "main" brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [aapt, p, -F, /home/flatzki/patchrom/ics_miui/.build/services.jar, /home/flatzki/patchrom/ics_miui/.build/services/build/apk]
    at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:193)
    at brut.androlib.Androlib.buildApk(Androlib.java:355)
    at brut.androlib.Androlib.build(Androlib.java:174)
    at brut.androlib.Androlib.build(Androlib.java:154)
    at brut.apktool.Main.cmdBuild(Main.java:182)
    at brut.apktool.Main.main(Main.java:67)
Caused by: brut.common.BrutException: could not exec command: [aapt, p, -F, /home/flatzki/patchrom/ics_miui/.build/services.jar, /home/flatzki/patchrom/ics_miui/.build/services/build/apk]
    at brut.util.OS.exec(OS.java:87)
    at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:191)
    ... 5 more
Caused by: java.io.IOException: Cannot run program "aapt": java.io.IOException: error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:475)
    at java.lang.Runtime.exec(Runtime.java:610)
    at java.lang.Runtime.exec(Runtime.java:483)
    at brut.util.OS.exec(OS.java:78)
    ... 6 more
Caused by: java.io.IOException: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:164)
    at java.lang.ProcessImpl.start(ProcessImpl.java:81)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:468)
    ... 9 more
make: **\* [.build/services.jar] Fehler 1
flatzki@flatzki-1015PE:~/patchrom/ics_miui$ 

help pls :) i found no answer

**Comment by Gerrett** [comment]
did you use a ics ROM?

**Comment by HackerMi** [comment]
The root cause is that system can't find the aapt tool.You can download android sdk,then unpack it. The aapt is under the tools folder. Add it to your system path,and try again.

**Comment by HackerMi** [comment]
Yes,We have developed ics ROM.
