### ISSUE TITLE
 makefile:41: /porting.mk: No such file or directory

### ISSUE THREAD

**Issue by jsrcodes** [MiCode/legacy-patchrom#2]
"sh build/envsetup.sh
cd i9100G 
make" 
got the below error after running above commands

makefile:41: /porting.mk: No such file or directory
make: **\* No rule to make target `/porting.mk'. Stop.

**Comment by fanoge** [comment]
Should use "source build/envsetup.sh" or ". build/envsetup.sh" instead of "sh .."

**Comment by jsrcodes** [comment]
I got it fixed by including the below lines to the makefile. 
PORT_BUILD=/home/jayasimha/thepatcher/build

PORT_ROOT=/home/jayasimha/thepatcher

But the making zip process went unsuccesful. I am attaching the output, please help me to fix it.

cp /home/jayasimha/thepatcher/miui/system/framework/framework-miui-res.apk .build/ZIP/system/framework/framework-miui-res.apk

## build .build/framework-res.apk...

cp -r framework-res .build
/home/jayasimha/thepatcher/tools/apktool b  .build/framework-res .build/framework-res.apk
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
aapt: warning: string 'wifi_available' has no default translation in /home/jayasimha/thepatcher/i9100G/.build/framework-res/res; found: ms
aapt: warning: string 'wifi_available_detailed' has no default translation in /home/jayasimha/thepatcher/i9100G/.build/framework-res/res; found: ms
I: Building apk file...
cp apks-unsinged to zip dirs
cp .build/framework-res.apk .build/ZIP/system/framework/framework-res.apk
/home/jayasimha/thepatcher/tools/apktool d -f /home/jayasimha/thepatcher/miui/system/app/MIUISystemUI.apk .build/SystemUI
I: Baksmaling...
I: Loading resource table...
I: Loaded.
I: Loading resource table from file: /home/jayasimha/apktool/framework/1.apk
I: Loaded.
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x060e006b
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x060e0075
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x060e0075
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x060e0075
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x060e0075
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x060e0075
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x060e0075
I: Decoding file-resources...
W: Could not decode attr value, using undecoded value instead: ns=android, name=textAppearance, value=0x060e0007
W: Could not decode attr value, using undecoded value instead: ns=android, name=textAppearance, value=0x060e0007
W: Could not decode attr value, using undecoded value instead: ns=android, name=drawable, value=0x0602037c
W: Could not decode attr value, using undecoded value instead: ns=android, name=textAppearance, value=0x060e0036
W: Could not decode attr value, using undecoded value instead: ns=android, name=textAppearance, value=0x060e0036
W: Could not decode attr value, using undecoded value instead: ns=android, name=textAppearance, value=0x060e0005
W: Could not decode attr value, using undecoded value instead: ns=android, name=textAppearance, value=0x060e0005
W: Could not decode attr value, using undecoded value instead: ns=android, name=textAppearance, value=0x060e0005
W: Could not decode attr value, using undecoded value instead: ns=android, name=textColor, value=0x0607003a
W: Could not decode attr value, using undecoded value instead: ns=android, name=textAppearance, value=0x060e0005
W: Could not decode attr value, using undecoded value instead: ns=android, name=textColor, value=0x0607003a
I: Decoding values_/_ XMLs...
Can't find framework resources for package of id: 6. You must install proper framework files, see project website for more info.
make: **\* [.build/SystemUI] Error 1

**Comment by jsrcodes** [comment]
I thought of installing miui framework for apktool and did so.. after that performed the make command, now i got different error 

cp /home/jayasimha/thepatcher/miui/system/framework/framework-miui-res.apk .build/ZIP/system/framework/framework-miui-res.apk

## build .build/framework-res.apk...

cp -r framework-res .build
/home/jayasimha/thepatcher/tools/apktool b  .build/framework-res .build/framework-res.apk
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
aapt: warning: string 'wifi_available' has no default translation in /home/jayasimha/thepatcher/i9100G/.build/framework-res/res; found: ms
aapt: warning: string 'wifi_available_detailed' has no default translation in /home/jayasimha/thepatcher/i9100G/.build/framework-res/res; found: ms
I: Building apk file...
cp apks-unsinged to zip dirs
cp .build/framework-res.apk .build/ZIP/system/framework/framework-res.apk

## build .build/MIUISystemUI.apk...

cp -r SystemUI .build
/home/jayasimha/thepatcher/tools/apktool b  .build/SystemUI .build/MIUISystemUI.apk
I: Checking whether sources has changed...
I: Smaling...
I: Checking whether resources has changed...
I: Building resources...
res/drawable-hdpi/status_bar_background.png:0: error: Resource entry status_bar_background is already defined.
res/drawable-hdpi/status_bar_background.9.png:0: Originally defined here.
/home/jayasimha/thepatcher/i9100G/.build/SystemUI/res/values/styles.xml:3: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Theme.Holo.Light.Panel'.
/home/jayasimha/thepatcher/i9100G/.build/SystemUI/res/values/styles.xml:8: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Theme.Holo.Light.Panel'.
Exception in thread "main" brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [aapt, p, -F, /tmp/APKTOOL2651416676899838457.tmp, -I, /home/jayasimha/apktool/framework/1.apk, -S, /home/jayasimha/thepatcher/i9100G/.build/SystemUI/res, -M, /home/jayasimha/thepatcher/i9100G/.build/SystemUI/AndroidManifest.xml]
    at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:193)
    at brut.androlib.Androlib.buildResourcesFull(Androlib.java:301)
    at brut.androlib.Androlib.buildResources(Androlib.java:248)
    at brut.androlib.Androlib.build(Androlib.java:171)
    at brut.androlib.Androlib.build(Androlib.java:154)
    at brut.apktool.Main.cmdBuild(Main.java:182)
    at brut.apktool.Main.main(Main.java:67)
Caused by: brut.common.BrutException: could not exec command: [aapt, p, -F, /tmp/APKTOOL2651416676899838457.tmp, -I, /home/jayasimha/apktool/framework/1.apk, -S, /home/jayasimha/thepatcher/i9100G/.build/SystemUI/res, -M, /home/jayasimha/thepatcher/i9100G/.build/SystemUI/AndroidManifest.xml]
    at brut.util.OS.exec(OS.java:83)
    at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:191)
    ... 6 more
make: **\* [.build/MIUISystemUI.apk] Error 1

**Comment by fanoge** [comment]
Strange to find status_bar_background.png exists in your res/drawable-hdpi with status_bar_background.9.png..

**Comment by jsrcodes** [comment]
Please help me.. the making of zip for default I9100 folder(given by micode) is fully working .. but i dont know why its not working with my i9100G model

**Comment by fanoge** [comment]
For SystemUI, I think it should be the same with i9100. Try to figure out why status_bar_background.png exists as reported by apktool..

**Comment by rpander93** [comment]
I'm also getting a lot of errors during the compilation of SystemUI.apk. All related to resource it can not find blablabla.

**Comment by RomBreaker** [comment]
Im Stuck there too
