### ISSUE TITLE
Error building SystemUI.apk

### ISSUE THREAD

**Issue by rpander93** [MiCode/legacy-patchrom#3]
I keep getting errors while the script tries to compile SystemUI.apk
All resources not found errors origin from files included in MIUI, and not in the original rom.

``` javascript
/home/remco/MiCode/tools/apktool b  .build/SystemUI .build/MIUISystemUI.apk
I: Checking whether sources has changed...
I: Smaling...
I: Checking whether resources has changed...
I: Building resources...
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_notifications.xml:2: error: Error: No resource found that matches the given name (at 'layout_marginBottom' with value '@dimen/notification_item_divider_height').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_notifications.xml:6: error: Error: No resource found that matches the given name (at 'id' with value '@id/usb_mode_notification').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_notifications.xml:7: error: Error: No resource found that matches the given name (at 'layout_width' with value '@dimen/notification_icon_size').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_notifications.xml:7: error: Error: No resource found that matches the given name (at 'layout_height' with value '@dimen/notification_icon_size').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_notifications.xml:8: error: Error: No resource found that matches the given name (at 'textAppearance' with value '@miui:style/TextAppearance.StatusBar.EventContent.Title').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_notifications.xml:8: error: Error: No resource found that matches the given name (at 'text' with value '@string/usb_mode_notification').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_notifications.xml:9: error: Error: No resource found that matches the given name (at 'id' with value '@id/usb_mode_button').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_toggles.xml:4: error: Error: No resource found that matches the given name (at 'id' with value '@id/toggle_list').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_toggles.xml:5: error: Error: No resource found that matches the given name (at 'id' with value '@id/toggle').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_toggles.xml:5: error: Error: No resource found that matches the given name (at 'style' with value '@style/StatusBarGridItem').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_toggles.xml:6: error: Error: No resource found that matches the given name (at 'id' with value '@id/toggle').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_toggles.xml:6: error: Error: No resource found that matches the given name (at 'style' with value '@style/StatusBarGridItem').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_toggles.xml:7: error: Error: No resource found that matches the given name (at 'id' with value '@id/toggle').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_toggles.xml:7: error: Error: No resource found that matches the given name (at 'style' with value '@style/StatusBarGridItem').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_toggles.xml:8: error: Error: No resource found that matches the given name (at 'id' with value '@id/toggle').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_toggles.xml:8: error: Error: No resource found that matches the given name (at 'style' with value '@style/StatusBarGridItem').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_toggles.xml:10: error: Error: No resource found that matches the given name (at 'id' with value '@id/toggle_list').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_toggles.xml:11: error: Error: No resource found that matches the given name (at 'id' with value '@id/toggle').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_toggles.xml:11: error: Error: No resource found that matches the given name (at 'style' with value '@style/StatusBarGridItem').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_toggles.xml:12: error: Error: No resource found that matches the given name (at 'id' with value '@id/toggle').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_toggles.xml:12: error: Error: No resource found that matches the given name (at 'style' with value '@style/StatusBarGridItem').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_toggles.xml:13: error: Error: No resource found that matches the given name (at 'id' with value '@id/toggle').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_toggles.xml:13: error: Error: No resource found that matches the given name (at 'style' with value '@style/StatusBarGridItem').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_toggles.xml:14: error: Error: No resource found that matches the given name (at 'id' with value '@id/toggle').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_toggles.xml:14: error: Error: No resource found that matches the given name (at 'style' with value '@style/StatusBarGridItem').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_toggles.xml:16: error: Error: No resource found that matches the given name (at 'id' with value '@id/toggle_list').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_toggles.xml:17: error: Error: No resource found that matches the given name (at 'id' with value '@id/toggle').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_toggles.xml:17: error: Error: No resource found that matches the given name (at 'style' with value '@style/StatusBarGridItem').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_toggles.xml:18: error: Error: No resource found that matches the given name (at 'id' with value '@id/toggle').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_toggles.xml:18: error: Error: No resource found that matches the given name (at 'style' with value '@style/StatusBarGridItem').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_toggles.xml:19: error: Error: No resource found that matches the given name (at 'id' with value '@id/toggle').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_toggles.xml:19: error: Error: No resource found that matches the given name (at 'style' with value '@style/StatusBarGridItem').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_toggles.xml:20: error: Error: No resource found that matches the given name (at 'id' with value '@id/brightness_toggle').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_toggles.xml:20: error: Error: No resource found that matches the given name (at 'style' with value '@style/StatusBarGridItem').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_toggles.xml:22: error: Error: No resource found that matches the given name (at 'id' with value '@id/manual_brightness_panel').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_expanded_toggles.xml:24: error: Error: No resource found that matches the given name (at 'id' with value '@id/manual_brightness').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_toggle.xml:2: error: Error: No resource found that matches the given name (at 'id' with value '@id/button_privacy_mode').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_toggle_divider.xml:4: error: Error: No resource found that matches the given name (at 'id' with value '@id/status_bar_toggle_divider_lable').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_toggle_divider.xml:4: error: Error: No resource found that matches the given name (at 'text' with value '@string/status_bar_toggle_divider_list').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_toggle_divider.xml:4: error: Error: No resource found that matches the given name (at 'style' with value '@*miui:style/TextAppearance.ListView.SecondaryItem').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_toggle_item.xml:2: error: Error: No resource found that matches the given name (at 'style' with value '@*miui:style/ListItem').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_toggle_item.xml:4: error: Error: No resource found that matches the given name (at 'id' with value '@id/icon').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_toggle_item.xml:5: error: Error: No resource found that matches the given name (at 'id' with value '@id/title').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_toggle_item.xml:5: error: Error: No resource found that matches the given name (at 'style' with value '@*miui:style/TextAppearance.ListView.PrimaryItem').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_toggle_item.xml:6: error: Error: No resource found that matches the given name (at 'id' with value '@id/drag_handle').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_toggle_style_preference.xml:4: error: Error: No resource found that matches the given name (at 'id' with value '@id/status_bar_toggle_style_compact').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_toggle_style_preference.xml:6: error: Error: No resource found that matches the given name (at 'textAppearance' with value '@miui:style/TextAppearance.Preference.PrimaryItem').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_toggle_style_preference.xml:6: error: Error: No resource found that matches the given name (at 'id' with value '@id/status_bar_toggle_style_compact_text').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_toggle_style_preference.xml:6: error: Error: No resource found that matches the given name (at 'text' with value '@string/status_bar_toggle_style_compact').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_toggle_style_preference.xml:8: error: Error: No resource found that matches the given name (at 'id' with value '@id/status_bar_toggle_style_single_page').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_toggle_style_preference.xml:10: error: Error: No resource found that matches the given name (at 'textAppearance' with value '@miui:style/TextAppearance.Preference.PrimaryItem').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_toggle_style_preference.xml:10: error: Error: No resource found that matches the given name (at 'id' with value '@id/status_bar_toggle_style_single_page_text').
/home/remco/MiCode/p990/.build/SystemUI/res/layout/status_bar_toggle_style_preference.xml:10: error: Error: No resource found that matches the given name (at 'text' with value '@string/status_bar_toggle_style_single_page').
/home/remco/MiCode/p990/.build/SystemUI/res/xml/toggle_settings.xml:2: error: Error: No resource found that matches the given name (at 'title' with value '@string/status_bar_toggle_settings').
/home/remco/MiCode/p990/.build/SystemUI/res/xml/toggle_settings.xml:5: error: Error: No resource found that matches the given name (at 'title' with value '@string/status_bar_toggle_style').
/home/remco/MiCode/p990/.build/SystemUI/res/xml/toggle_settings.xml:6: error: Error: No resource found that matches the given name (at 'title' with value '@string/status_bar_toggle_style').
/home/remco/MiCode/p990/.build/SystemUI/res/xml/toggle_settings.xml:9: error: Error: No resource found that matches the given name (at 'title' with value '@string/status_bar_toggle_arrangement').
/home/remco/MiCode/p990/.build/SystemUI/res/xml/toggle_settings.xml:12: error: Error: No resource found that matches the given name (at 'title' with value '@string/battery_indicator_style').
/home/remco/MiCode/p990/.build/SystemUI/res/xml/toggle_settings.xml:13: error: Error: No resource found that matches the given name (at 'title' with value '@string/default_usb_mode').
/home/remco/MiCode/p990/.build/SystemUI/res/xml/toggle_settings.xml:14: error: Error: No resource found that matches the given name (at 'title' with value '@string/expandable_under_fullscreen').
/home/remco/MiCode/p990/.build/SystemUI/res/xml/toggle_settings.xml:14: error: Error: No resource found that matches the given name (at 'summary' with value '@string/expandable_under_fullscreen_summary').
/home/remco/MiCode/p990/.build/SystemUI/res/xml/toggle_settings.xml:15: error: Error: No resource found that matches the given name (at 'title' with value '@string/enable_back_long_press').
/home/remco/MiCode/p990/.build/SystemUI/res/color/tab_lable_color.xml:4: error: Error: No resource found that matches the given name (at 'color' with value '@color/tab_lable_color_p').
/home/remco/MiCode/p990/.build/SystemUI/res/color/tab_lable_color.xml:5: error: Error: No resource found that matches the given name (at 'color' with value '@color/tab_lable_color_p').
/home/remco/MiCode/p990/.build/SystemUI/res/color/tab_lable_color.xml:6: error: Error: No resource found that matches the given name (at 'color' with value '@color/tab_lable_color_n').
Exception in thread "main" brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [aapt, p, -F, /tmp/APKTOOL786352555857971186.tmp, -I, /home/remco/apktool/framework/1-p990.apk, -S, /home/remco/MiCode/p990/.build/SystemUI/res, -M, /home/remco/MiCode/p990/.build/SystemUI/AndroidManifest.xml]
    at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:193)
    at brut.androlib.Androlib.buildResourcesFull(Androlib.java:301)
    at brut.androlib.Androlib.buildResources(Androlib.java:248)
    at brut.androlib.Androlib.build(Androlib.java:171)
    at brut.androlib.Androlib.build(Androlib.java:154)
    at brut.apktool.Main.cmdBuild(Main.java:182)

    at brut.apktool.Main.main(Main.java:67)
Caused by: brut.common.BrutException: could not exec command: [aapt, p, -F, /tmp/APKTOOL786352555857971186.tmp, -I, /home/remco/apktool/framework/1-p990.apk, -S, /home/remco/MiCode/p990/.build/SystemUI/res, -M, /home/remco/MiCode/p990/.build/SystemUI/AndroidManifest.xml]
    at brut.util.OS.exec(OS.java:83)
    at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:191)
    ... 6 more
make: *** [.build/MIUISystemUI.apk] Error 1
```

**Comment by chirayudesai** [comment]
could not exec command: [aapt

have you got the aapt binary, and added it to path?
Install the sdk, then export PATH=$PATH:/path/to/sdk/platform-tools:/path/to/sdk/tools

**Comment by rpander93** [comment]
Yes, I have installed everything. Java, the android sdk, updated my PATH. This is the last apk that has to be compiled before it starts adding media and the compressing the ZIP.

I just did some dirty modifications so the script would skip SystemUI.apk. Then I put MIUISystemUI.apk from another rom into the .build folder and ran the script again. It provided me with a zip-file but ofcourse this was giving me a lot of errors when trying to boot it on my LG 2x. (acore process crashing etc.)

**Comment by chirayudesai** [comment]
yea, i've been facing this too, got a lot of resource not found errors (as i'm porting to a ldpi device), waiting for an official answer

**Comment by rpander93** [comment]
Hmm, I first tried compiling a MIUI ROM from CM7 base, but this gave me a whole bunch of errors. So now I'm trying to compile from an official LG rom and this is the only issue I have.

**Comment by MiningCryptoLive** [comment]
Same here, Get as far as compiling SystemUI.apk and then it errors saying "I: Decoding values_/_ XMLs...
Can't find framework resources for package of id: 6. You must install proper framework files, see project website for more info.
make: **\* [.build/SystemUI] Error 1"

Any help would be appreciated

**Comment by rpander93** [comment]
@Racing1 

You'll have to install the framework with apktool first:

"apktool if <framework-res.apk location>"

**Comment by chirayudesai** [comment]
use this

make apktool-if /path/to/framework-res.apk

then do the usual

make

**Comment by MiningCryptoLive** [comment]
People, Stop telling me to install framework. I am not a newbie. Framework is installed. There is something in the framework files causing it not to build.

**Comment by maximik1980** [comment]
I think you should add to your strings.xml array.xml etc. the strings that are in the original MIUIsystemUI.apk. As for me, I'm also trying to build a MIUI patch ROM and I have the same problems...
