### ISSUE TITLE
make: *** [.build/Phone.apk] Error 1

### ISSUE THREAD

**Issue by sphanley** [MiCode/legacy-patchrom#5]
I'm trying to build a patchrom for the Samsung i510 platform. I'm having seeming success up until it tries to rebuild the phone.apk, at which point I get the following error.

I'm going to try it with a different base rom to see if maybe it's an issue with the Phone.apk I'm trying to use, but if anyone has any ideas I'd greatly appreciate it.

Error as follows: 

---

cp -r Phone .build
/Users/sam/Development/micode-patchrom-1b14930/tools/apktool b  .build/Phone .build/Phone.apk
I: Checking whether sources has changed...
I: Smaling...
I: Checking whether resources has changed...
I: Building resources...
/Users/sam/Development/MiCode-PatchRom-1b14930/i510/.build/Phone/res/values-es-rUS/strings.xml:236: error: Multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?
/Users/sam/Development/MiCode-PatchRom-1b14930/i510/.build/Phone/res/values-es-rUS/strings.xml:237: error: Unexpected end tag string
aapt: warning: string 'start_webex' has no default translation in /Users/sam/Development/MiCode-PatchRom-1b14930/i510/.build/Phone/res; found: es
Exception in thread "main" brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [aapt, p, -F, /var/folders/p6/07ntc38j61j13pcgkf4v743r0000gn/T/APKTOOL5169369411525875068.tmp, -I, /Users/sam/apktool/framework/1.apk, -I, /Users/sam/apktool/framework/2.apk, -S, /Users/sam/Development/MiCode-PatchRom-1b14930/i510/.build/Phone/res, -M, /Users/sam/Development/MiCode-PatchRom-1b14930/i510/.build/Phone/AndroidManifest.xml]
    at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:193)
    at brut.androlib.Androlib.buildResourcesFull(Androlib.java:301)
    at brut.androlib.Androlib.buildResources(Androlib.java:248)
    at brut.androlib.Androlib.build(Androlib.java:171)
    at brut.androlib.Androlib.build(Androlib.java:154)
    at brut.apktool.Main.cmdBuild(Main.java:182)
    at brut.apktool.Main.main(Main.java:67)
Caused by: brut.common.BrutException: could not exec command: [aapt, p, -F, /var/folders/p6/07ntc38j61j13pcgkf4v743r0000gn/T/APKTOOL5169369411525875068.tmp, -I, /Users/sam/apktool/framework/1.apk, -I, /Users/sam/apktool/framework/2.apk, -S, /Users/sam/Development/MiCode-PatchRom-1b14930/i510/.build/Phone/res, -M, /Users/sam/Development/MiCode-PatchRom-1b14930/i510/.build/Phone/AndroidManifest.xml]
    at brut.util.OS.exec(OS.java:83)
    at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:191)
    ... 6 more
make: **\* [.build/Phone.apk] Error 1

**Comment by rpander93** [comment]
Some .xml errors. Check the file for errors and fix them. Shouldn't be too hard.

**Comment by sphanley** [comment]
Thanks. Fixed.
