### ISSUE TITLE
Error building BlurPhone.apk

### ISSUE THREAD

**Issue by M1cha** [MiCode/legacy-patchrom#7]
I'm getting the following error while building for defy:
Exception in thread "main" brut.androlib.err.CantFindFrameworkResException
        at brut.androlib.res.AndrolibResources.getFrameworkApk(AndrolibResources.java:366)
        at brut.androlib.Androlib.parseUsesFramework(Androlib.java:400)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:301)
        at brut.androlib.Androlib.buildResources(Androlib.java:248)
        at brut.androlib.Androlib.build(Androlib.java:171)
        at brut.androlib.Androlib.build(Androlib.java:154)
        at brut.apktool.Main.cmdBuild(Main.java:182)
        at brut.apktool.Main.main(Main.java:67)

I already added framework-res.apk and moto-res.apk with apktool but it still doesn't work.

**Comment by M1cha** [comment]
Sorry, I forgot to add blur-res.apk to framework-resources.
