### ISSUE TITLE
Can't build framework.jar

### ISSUE THREAD

**Issue by Gerrett** [MiCode/legacy-patchrom#9]
Building Framework.jar :

cp -r framework.jar.out/ .build/framework
/home/nimrod/MIUI-Vengeance/MiPatcher/tools/add_miui_smail.sh .build/framework_miui .build/framework
/home/nimrod/MIUI-Vengeance/MiPatcher/tools/apktool b .build/framework .build/framework.jar
I: Checking whether sources has changed...
I: Smaling...
Exception in thread "main" org.jf.dexlib.Util.ExceptionWithContext: method index is too large.
    at org.jf.dexlib.Util.ExceptionWithContext.withContext(ExceptionWithContext.java:54)
    at org.jf.dexlib.Item.addExceptionContext(Item.java:176)
    at org.jf.dexlib.Item.writeTo(Item.java:119)
    at org.jf.dexlib.Section.writeTo(Section.java:119)
    at org.jf.dexlib.DexFile.writeTo(DexFile.java:716)
    at brut.androlib.src.DexFileBuilder.getAsByteArray(DexFileBuilder.java:75)
    at brut.androlib.src.DexFileBuilder.writeTo(DexFileBuilder.java:58)
    at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:50)
    at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:35)
    at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:222)
    at brut.androlib.Androlib.buildSources(Androlib.java:179)
    at brut.androlib.Androlib.build(Androlib.java:170)
    at brut.androlib.Androlib.build(Androlib.java:154)
    at brut.apktool.Main.cmdBuild(Main.java:182)
    at brut.apktool.Main.main(Main.java:67)
Caused by: java.lang.RuntimeException: method index is too large.
    at org.jf.dexlib.Code.Format.Instruction35c.writeInstruction(Instruction35c.java:102)
    at org.jf.dexlib.Code.Instruction.write(Instruction.java:57)
    at org.jf.dexlib.CodeItem.writeItem(CodeItem.java:258)
    at org.jf.dexlib.Item.writeTo(Item.java:116)
    ... 12 more
code_item @0x1caf34 (Landroid/net/NetworkInfo$DetailedState;->values()[Landroid/net/NetworkInfo$DetailedState;)

make: **\* [.build/framework.jar] Fehler 1

On LG Optimus 3D , Stock rom

**Comment by HackerMi** [comment]
This is a apktool bug. There are too many files in framework.jar,and the apktool can't process it.
There is a method may resolve it.Please try it.
1.make clean
2."make .build/framework.jar ",and ignore the error.
3."cd .build/","mkdir framework-miui","mv framework/smali/miui framework-miui"
4.use apktool compiles "framework" and "framework-miui",and push the framework.jar and framework-miui.jar to /system/framework
5.modify boot.img and add framework-miui.jar to "init.rc" BOOTCLASSPATH.

**Comment by Gerrett** [comment]
thanks for your fast answer! I think "mv framework/smali/miui framework-miui" must be " mv framework/smali/miui framework-miui/smali" and add a apktool.yml compiling seems to be ok now (can i take the original framework.jar + the framework-miui.jar ? ) 
but no i got a bootloop and can't logcat. will try tomorrow again and start from beginning with hope something went wrong.

**Comment by Gerrett** [comment]
if i add the changed Boot.img and the framework-miui.jar and flash it, it stucks at LG Logo. adb doesn't work, so i didn't have a logcat.
any idea?

**Comment by HackerMi** [comment]
It may be the kernel does not match you phone.Try "recovery  backup tool" backup the boot image which can work,then modify it.

**Comment by Gerrett** [comment]
without changing the init.rc the phone boots up, but with lots of fc's cause of the missing framework files

**Comment by Gerrett** [comment]
i think there must be a problem with the framework-miui.jar (

**Comment by Gerrett** [comment]
Got it. removed unneeded stuff from framework.jar .. now i can build it and its Booting
